import { Pokemon } from "./Pokemon.model";

export const pokemonList: Pokemon[] = [
  {
    id: 1,
    name: "bulbasaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png",
    types: ["grass", "poison"],
    weight: 69,
    height: 7,
    abilities: ["overgrow", "chlorophyll"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 49 },
      { name: "defense", value: 49 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 45 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 2,
    name: "ivysaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png",
    types: ["grass", "poison"],
    weight: 130,
    height: 10,
    abilities: ["overgrow", "chlorophyll"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 62 },
      { name: "defense", value: 63 },
      { name: "special-attack", value: 80 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 60 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 3,
    name: "venusaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png",
    types: ["grass", "poison"],
    weight: 1000,
    height: 20,
    abilities: ["overgrow", "chlorophyll"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 82 },
      { name: "defense", value: 83 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 80 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 4,
    name: "charmander",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png",
    types: ["fire"],
    weight: 85,
    height: 6,
    abilities: ["blaze", "solar-power"],
    stats: [
      { name: "hp", value: 39 },
      { name: "attack", value: 52 },
      { name: "defense", value: 43 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 65 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 5,
    name: "charmeleon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png",
    types: ["fire"],
    weight: 190,
    height: 11,
    abilities: ["blaze", "solar-power"],
    stats: [
      { name: "hp", value: 58 },
      { name: "attack", value: 64 },
      { name: "defense", value: 58 },
      { name: "special-attack", value: 80 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 80 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 6,
    name: "charizard",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png",
    types: ["fire", "flying"],
    weight: 905,
    height: 17,
    abilities: ["blaze", "solar-power"],
    stats: [
      { name: "hp", value: 78 },
      { name: "attack", value: 84 },
      { name: "defense", value: 78 },
      { name: "special-attack", value: 109 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 100 },
    ],
    weak: ["ground", "rock", "water", "rock", "electric", "ice"],
    strong: ["bug", "steel", "grass", "ice", "fighting", "bug", "grass"],
  },
  {
    id: 7,
    name: "squirtle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png",
    types: ["water"],
    weight: 90,
    height: 5,
    abilities: ["torrent", "rain-dish"],
    stats: [
      { name: "hp", value: 44 },
      { name: "attack", value: 48 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 64 },
      { name: "speed", value: 43 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 8,
    name: "wartortle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png",
    types: ["water"],
    weight: 225,
    height: 10,
    abilities: ["torrent", "rain-dish"],
    stats: [
      { name: "hp", value: 59 },
      { name: "attack", value: 63 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 58 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 9,
    name: "blastoise",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png",
    types: ["water"],
    weight: 855,
    height: 16,
    abilities: ["torrent", "rain-dish"],
    stats: [
      { name: "hp", value: 79 },
      { name: "attack", value: 83 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 105 },
      { name: "speed", value: 78 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 10,
    name: "caterpie",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png",
    types: ["bug"],
    weight: 29,
    height: 3,
    abilities: ["shield-dust", "run-away"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 30 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 20 },
      { name: "special-defense", value: 20 },
      { name: "speed", value: 45 },
    ],
    weak: ["flying", "rock", "fire"],
    strong: ["grass", "psychic", "dark"],
  },
  {
    id: 11,
    name: "metapod",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/11.png",
    types: ["bug"],
    weight: 99,
    height: 7,
    abilities: ["shed-skin"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 20 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 25 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 30 },
    ],
    weak: ["flying", "rock", "fire"],
    strong: ["grass", "psychic", "dark"],
  },
  {
    id: 12,
    name: "butterfree",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/12.png",
    types: ["bug", "flying"],
    weight: 320,
    height: 11,
    abilities: ["compound-eyes", "tinted-lens"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 45 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 90 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 70 },
    ],
    weak: ["flying", "rock", "fire", "rock", "electric", "ice"],
    strong: ["grass", "psychic", "dark", "fighting", "bug", "grass"],
  },
  {
    id: 13,
    name: "weedle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/13.png",
    types: ["bug", "poison"],
    weight: 32,
    height: 3,
    abilities: ["shield-dust", "run-away"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 35 },
      { name: "defense", value: 30 },
      { name: "special-attack", value: 20 },
      { name: "special-defense", value: 20 },
      { name: "speed", value: 50 },
    ],
    weak: ["flying", "rock", "fire", "ground", "psychic"],
    strong: ["grass", "psychic", "dark", "grass", "fairy"],
  },
  {
    id: 14,
    name: "kakuna",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/14.png",
    types: ["bug", "poison"],
    weight: 100,
    height: 6,
    abilities: ["shed-skin"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 25 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 25 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 35 },
    ],
    weak: ["flying", "rock", "fire", "ground", "psychic"],
    strong: ["grass", "psychic", "dark", "grass", "fairy"],
  },
  {
    id: 15,
    name: "beedrill",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png",
    types: ["bug", "poison"],
    weight: 295,
    height: 10,
    abilities: ["swarm", "sniper"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 90 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 75 },
    ],
    weak: ["flying", "rock", "fire", "ground", "psychic"],
    strong: ["grass", "psychic", "dark", "grass", "fairy"],
  },
  {
    id: 16,
    name: "pidgey",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/16.png",
    types: ["normal", "flying"],
    weight: 18,
    height: 3,
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 45 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 35 },
      { name: "speed", value: 56 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 17,
    name: "pidgeotto",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/17.png",
    types: ["normal", "flying"],
    weight: 300,
    height: 11,
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: [
      { name: "hp", value: 63 },
      { name: "attack", value: 60 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 71 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 18,
    name: "pidgeot",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png",
    types: ["normal", "flying"],
    weight: 395,
    height: 15,
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: [
      { name: "hp", value: 83 },
      { name: "attack", value: 80 },
      { name: "defense", value: 75 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 101 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 19,
    name: "rattata",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/19.png",
    types: ["normal"],
    weight: 35,
    height: 3,
    abilities: ["run-away", "guts", "hustle"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 56 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 25 },
      { name: "special-defense", value: 35 },
      { name: "speed", value: 72 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 20,
    name: "raticate",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/20.png",
    types: ["normal"],
    weight: 185,
    height: 7,
    abilities: ["run-away", "guts", "hustle"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 81 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 97 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 21,
    name: "spearow",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/21.png",
    types: ["normal", "flying"],
    weight: 20,
    height: 3,
    abilities: ["keen-eye", "sniper"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 60 },
      { name: "defense", value: 30 },
      { name: "special-attack", value: 31 },
      { name: "special-defense", value: 31 },
      { name: "speed", value: 70 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 22,
    name: "fearow",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/22.png",
    types: ["normal", "flying"],
    weight: 380,
    height: 12,
    abilities: ["keen-eye", "sniper"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 90 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 61 },
      { name: "special-defense", value: 61 },
      { name: "speed", value: 100 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 23,
    name: "ekans",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/23.png",
    types: ["poison"],
    weight: 69,
    height: 20,
    abilities: ["intimidate", "shed-skin", "unnerve"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 60 },
      { name: "defense", value: 44 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 54 },
      { name: "speed", value: 55 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 24,
    name: "arbok",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/24.png",
    types: ["poison"],
    weight: 650,
    height: 35,
    abilities: ["intimidate", "shed-skin", "unnerve"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 95 },
      { name: "defense", value: 69 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 79 },
      { name: "speed", value: 80 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 25,
    name: "pikachu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png",
    types: ["electric"],
    weight: 60,
    height: 4,
    abilities: ["static", "lightning-rod"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 55 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 90 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 26,
    name: "raichu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png",
    types: ["electric"],
    weight: 300,
    height: 8,
    abilities: ["static", "lightning-rod"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 90 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 90 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 110 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 27,
    name: "sandshrew",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/27.png",
    types: ["ground"],
    weight: 120,
    height: 6,
    abilities: ["sand-veil", "sand-rush"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 75 },
      { name: "defense", value: 85 },
      { name: "special-attack", value: 20 },
      { name: "special-defense", value: 30 },
      { name: "speed", value: 40 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 28,
    name: "sandslash",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/28.png",
    types: ["ground"],
    weight: 295,
    height: 10,
    abilities: ["sand-veil", "sand-rush"],
    stats: [
      { name: "hp", value: 75 },
      { name: "attack", value: 100 },
      { name: "defense", value: 110 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 65 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 29,
    name: "nidoran-f",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/29.png",
    types: ["poison"],
    weight: 70,
    height: 4,
    abilities: ["poison-point", "rivalry", "hustle"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 47 },
      { name: "defense", value: 52 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 41 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 30,
    name: "nidorina",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/30.png",
    types: ["poison"],
    weight: 200,
    height: 8,
    abilities: ["poison-point", "rivalry", "hustle"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 62 },
      { name: "defense", value: 67 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 56 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 31,
    name: "nidoqueen",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/31.png",
    types: ["poison", "ground"],
    weight: 600,
    height: 13,
    abilities: ["poison-point", "rivalry", "sheer-force"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 92 },
      { name: "defense", value: 87 },
      { name: "special-attack", value: 75 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 76 },
    ],
    weak: ["ground", "psychic", "water", "grass", "ice"],
    strong: ["grass", "fairy", "poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 32,
    name: "nidoran-m",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/32.png",
    types: ["poison"],
    weight: 90,
    height: 5,
    abilities: ["poison-point", "rivalry", "hustle"],
    stats: [
      { name: "hp", value: 46 },
      { name: "attack", value: 57 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 50 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 33,
    name: "nidorino",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/33.png",
    types: ["poison"],
    weight: 195,
    height: 9,
    abilities: ["poison-point", "rivalry", "hustle"],
    stats: [
      { name: "hp", value: 61 },
      { name: "attack", value: 72 },
      { name: "defense", value: 57 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 65 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 34,
    name: "nidoking",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/34.png",
    types: ["poison", "ground"],
    weight: 620,
    height: 14,
    abilities: ["poison-point", "rivalry", "sheer-force"],
    stats: [
      { name: "hp", value: 81 },
      { name: "attack", value: 102 },
      { name: "defense", value: 77 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 85 },
    ],
    weak: ["ground", "psychic", "water", "grass", "ice"],
    strong: ["grass", "fairy", "poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 35,
    name: "clefairy",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/35.png",
    types: ["fairy"],
    weight: 75,
    height: 6,
    abilities: ["cute-charm", "magic-guard", "friend-guard"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 45 },
      { name: "defense", value: 48 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 35 },
    ],
    weak: ["poison", "steel"],
    strong: ["fighting", "dragon", "dark"],
  },
  {
    id: 36,
    name: "clefable",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/36.png",
    types: ["fairy"],
    weight: 400,
    height: 13,
    abilities: ["cute-charm", "magic-guard", "unaware"],
    stats: [
      { name: "hp", value: 95 },
      { name: "attack", value: 70 },
      { name: "defense", value: 73 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 60 },
    ],
    weak: ["poison", "steel"],
    strong: ["fighting", "dragon", "dark"],
  },
  {
    id: 37,
    name: "vulpix",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/37.png",
    types: ["fire"],
    weight: 99,
    height: 6,
    abilities: ["flash-fire", "drought"],
    stats: [
      { name: "hp", value: 38 },
      { name: "attack", value: 41 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 65 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 38,
    name: "ninetales",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/38.png",
    types: ["fire"],
    weight: 199,
    height: 11,
    abilities: ["flash-fire", "drought"],
    stats: [
      { name: "hp", value: 73 },
      { name: "attack", value: 76 },
      { name: "defense", value: 75 },
      { name: "special-attack", value: 81 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 100 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 39,
    name: "jigglypuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/39.png",
    types: ["normal", "fairy"],
    weight: 55,
    height: 5,
    abilities: ["cute-charm", "competitive", "friend-guard"],
    stats: [
      { name: "hp", value: 115 },
      { name: "attack", value: 45 },
      { name: "defense", value: 20 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 20 },
    ],
    weak: ["fighting", "poison", "steel"],
    strong: ["fighting", "dragon", "dark"],
  },
  {
    id: 40,
    name: "wigglytuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/40.png",
    types: ["normal", "fairy"],
    weight: 120,
    height: 10,
    abilities: ["cute-charm", "competitive", "frisk"],
    stats: [
      { name: "hp", value: 140 },
      { name: "attack", value: 70 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 45 },
    ],
    weak: ["fighting", "poison", "steel"],
    strong: ["fighting", "dragon", "dark"],
  },
  {
    id: 41,
    name: "zubat",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/41.png",
    types: ["poison", "flying"],
    weight: 75,
    height: 8,
    abilities: ["inner-focus", "infiltrator"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 45 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 30 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 55 },
    ],
    weak: ["ground", "psychic", "rock", "electric", "ice"],
    strong: ["grass", "fairy", "fighting", "bug", "grass"],
  },
  {
    id: 42,
    name: "golbat",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/42.png",
    types: ["poison", "flying"],
    weight: 550,
    height: 16,
    abilities: ["inner-focus", "infiltrator"],
    stats: [
      { name: "hp", value: 75 },
      { name: "attack", value: 80 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 90 },
    ],
    weak: ["ground", "psychic", "rock", "electric", "ice"],
    strong: ["grass", "fairy", "fighting", "bug", "grass"],
  },
  {
    id: 43,
    name: "oddish",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/43.png",
    types: ["grass", "poison"],
    weight: 54,
    height: 5,
    abilities: ["chlorophyll", "run-away"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 50 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 75 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 30 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 44,
    name: "gloom",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/44.png",
    types: ["grass", "poison"],
    weight: 86,
    height: 8,
    abilities: ["chlorophyll", "stench"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 65 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 40 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 45,
    name: "vileplume",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/45.png",
    types: ["grass", "poison"],
    weight: 186,
    height: 12,
    abilities: ["chlorophyll", "effect-spore"],
    stats: [
      { name: "hp", value: 75 },
      { name: "attack", value: 80 },
      { name: "defense", value: 85 },
      { name: "special-attack", value: 110 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 50 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 46,
    name: "paras",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/46.png",
    types: ["bug", "grass"],
    weight: 54,
    height: 3,
    abilities: ["effect-spore", "dry-skin", "damp"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 70 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 25 },
    ],
    weak: ["flying", "rock", "fire", "flying", "poison", "bug", "fire", "ice"],
    strong: ["grass", "psychic", "dark", "ground", "rock", "water"],
  },
  {
    id: 47,
    name: "parasect",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/47.png",
    types: ["bug", "grass"],
    weight: 295,
    height: 10,
    abilities: ["effect-spore", "dry-skin", "damp"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 95 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 30 },
    ],
    weak: ["flying", "rock", "fire", "flying", "poison", "bug", "fire", "ice"],
    strong: ["grass", "psychic", "dark", "ground", "rock", "water"],
  },
  {
    id: 48,
    name: "venonat",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/48.png",
    types: ["bug", "poison"],
    weight: 300,
    height: 10,
    abilities: ["compound-eyes", "tinted-lens", "run-away"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 55 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 45 },
    ],
    weak: ["flying", "rock", "fire", "ground", "psychic"],
    strong: ["grass", "psychic", "dark", "grass", "fairy"],
  },
  {
    id: 49,
    name: "venomoth",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/49.png",
    types: ["bug", "poison"],
    weight: 125,
    height: 15,
    abilities: ["shield-dust", "tinted-lens", "wonder-skin"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 65 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 90 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 90 },
    ],
    weak: ["flying", "rock", "fire", "ground", "psychic"],
    strong: ["grass", "psychic", "dark", "grass", "fairy"],
  },
  {
    id: 50,
    name: "diglett",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/50.png",
    types: ["ground"],
    weight: 8,
    height: 2,
    abilities: ["sand-veil", "arena-trap", "sand-force"],
    stats: [
      { name: "hp", value: 10 },
      { name: "attack", value: 55 },
      { name: "defense", value: 25 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 95 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 51,
    name: "dugtrio",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/51.png",
    types: ["ground"],
    weight: 333,
    height: 7,
    abilities: ["sand-veil", "arena-trap", "sand-force"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 100 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 120 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 52,
    name: "meowth",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/52.png",
    types: ["normal"],
    weight: 42,
    height: 4,
    abilities: ["pickup", "technician", "unnerve"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 45 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 90 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 53,
    name: "persian",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/53.png",
    types: ["normal"],
    weight: 320,
    height: 10,
    abilities: ["limber", "technician", "unnerve"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 70 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 115 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 54,
    name: "psyduck",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/54.png",
    types: ["water"],
    weight: 196,
    height: 8,
    abilities: ["damp", "cloud-nine", "swift-swim"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 52 },
      { name: "defense", value: 48 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 55 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 55,
    name: "golduck",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/55.png",
    types: ["water"],
    weight: 766,
    height: 17,
    abilities: ["damp", "cloud-nine", "swift-swim"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 82 },
      { name: "defense", value: 78 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 85 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 56,
    name: "mankey",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/56.png",
    types: ["fighting"],
    weight: 280,
    height: 5,
    abilities: ["vital-spirit", "anger-point", "defiant"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 80 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 70 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 57,
    name: "primeape",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/57.png",
    types: ["fighting"],
    weight: 320,
    height: 10,
    abilities: ["vital-spirit", "anger-point", "defiant"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 105 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 95 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 58,
    name: "growlithe",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/58.png",
    types: ["fire"],
    weight: 190,
    height: 7,
    abilities: ["intimidate", "flash-fire", "justified"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 70 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 60 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 59,
    name: "arcanine",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/59.png",
    types: ["fire"],
    weight: 1550,
    height: 19,
    abilities: ["intimidate", "flash-fire", "justified"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 110 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 95 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 60,
    name: "poliwag",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/60.png",
    types: ["water"],
    weight: 124,
    height: 6,
    abilities: ["water-absorb", "damp", "swift-swim"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 50 },
      { name: "defense", value: 40 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 90 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 61,
    name: "poliwhirl",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/61.png",
    types: ["water"],
    weight: 200,
    height: 10,
    abilities: ["water-absorb", "damp", "swift-swim"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 65 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 90 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 62,
    name: "poliwrath",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/62.png",
    types: ["water", "fighting"],
    weight: 540,
    height: 13,
    abilities: ["water-absorb", "damp", "swift-swim"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 95 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 70 },
    ],
    weak: ["grass", "electric", "flying", "psychic", "fairy"],
    strong: [
      "ground",
      "rock",
      "fire",
      "normal",
      "rock",
      "steel",
      "ice",
      "dark",
    ],
  },
  {
    id: 63,
    name: "abra",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/63.png",
    types: ["psychic"],
    weight: 195,
    height: 9,
    abilities: ["synchronize", "inner-focus", "magic-guard"],
    stats: [
      { name: "hp", value: 25 },
      { name: "attack", value: 20 },
      { name: "defense", value: 15 },
      { name: "special-attack", value: 105 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 90 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 64,
    name: "kadabra",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/64.png",
    types: ["psychic"],
    weight: 565,
    height: 13,
    abilities: ["synchronize", "inner-focus", "magic-guard"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 35 },
      { name: "defense", value: 30 },
      { name: "special-attack", value: 120 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 105 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 65,
    name: "alakazam",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/65.png",
    types: ["psychic"],
    weight: 480,
    height: 15,
    abilities: ["synchronize", "inner-focus", "magic-guard"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 50 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 135 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 120 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 66,
    name: "machop",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/66.png",
    types: ["fighting"],
    weight: 195,
    height: 8,
    abilities: ["guts", "no-guard", "steadfast"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 80 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 35 },
      { name: "speed", value: 35 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 67,
    name: "machoke",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/67.png",
    types: ["fighting"],
    weight: 705,
    height: 15,
    abilities: ["guts", "no-guard", "steadfast"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 100 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 60 },
      { name: "speed", value: 45 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 68,
    name: "machamp",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/68.png",
    types: ["fighting"],
    weight: 1300,
    height: 16,
    abilities: ["guts", "no-guard", "steadfast"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 130 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 55 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 69,
    name: "bellsprout",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/69.png",
    types: ["grass", "poison"],
    weight: 40,
    height: 7,
    abilities: ["chlorophyll", "gluttony"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 75 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 30 },
      { name: "speed", value: 40 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 70,
    name: "weepinbell",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/70.png",
    types: ["grass", "poison"],
    weight: 64,
    height: 10,
    abilities: ["chlorophyll", "gluttony"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 90 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 55 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 71,
    name: "victreebel",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/71.png",
    types: ["grass", "poison"],
    weight: 155,
    height: 17,
    abilities: ["chlorophyll", "gluttony"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 105 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 70 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "ground", "psychic"],
    strong: ["ground", "rock", "water", "grass", "fairy"],
  },
  {
    id: 72,
    name: "tentacool",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/72.png",
    types: ["water", "poison"],
    weight: 455,
    height: 9,
    abilities: ["clear-body", "liquid-ooze", "rain-dish"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 40 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 70 },
    ],
    weak: ["grass", "electric", "ground", "psychic"],
    strong: ["ground", "rock", "fire", "grass", "fairy"],
  },
  {
    id: 73,
    name: "tentacruel",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/73.png",
    types: ["water", "poison"],
    weight: 550,
    height: 16,
    abilities: ["clear-body", "liquid-ooze", "rain-dish"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 70 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 80 },
      { name: "special-defense", value: 120 },
      { name: "speed", value: 100 },
    ],
    weak: ["grass", "electric", "ground", "psychic"],
    strong: ["ground", "rock", "fire", "grass", "fairy"],
  },
  {
    id: 74,
    name: "geodude",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/74.png",
    types: ["rock", "ground"],
    weight: 200,
    height: 4,
    abilities: ["rock-head", "sturdy", "sand-veil"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 80 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 30 },
      { name: "special-defense", value: 30 },
      { name: "speed", value: 20 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "water",
      "grass",
      "ice",
    ],
    strong: [
      "flying",
      "bug",
      "fire",
      "ice",
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
    ],
  },
  {
    id: 75,
    name: "graveler",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/75.png",
    types: ["rock", "ground"],
    weight: 1050,
    height: 10,
    abilities: ["rock-head", "sturdy", "sand-veil"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 95 },
      { name: "defense", value: 115 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 35 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "water",
      "grass",
      "ice",
    ],
    strong: [
      "flying",
      "bug",
      "fire",
      "ice",
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
    ],
  },
  {
    id: 76,
    name: "golem",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/76.png",
    types: ["rock", "ground"],
    weight: 3000,
    height: 14,
    abilities: ["rock-head", "sturdy", "sand-veil"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 120 },
      { name: "defense", value: 130 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 45 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "water",
      "grass",
      "ice",
    ],
    strong: [
      "flying",
      "bug",
      "fire",
      "ice",
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
    ],
  },
  {
    id: 77,
    name: "ponyta",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/77.png",
    types: ["fire"],
    weight: 300,
    height: 10,
    abilities: ["run-away", "flash-fire", "flame-body"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 85 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 90 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 78,
    name: "rapidash",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/78.png",
    types: ["fire"],
    weight: 950,
    height: 17,
    abilities: ["run-away", "flash-fire", "flame-body"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 100 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 80 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 105 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 79,
    name: "slowpoke",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/79.png",
    types: ["water", "psychic"],
    weight: 360,
    height: 12,
    abilities: ["oblivious", "own-tempo", "regenerator"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 65 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 15 },
    ],
    weak: ["grass", "electric", "bug", "ghost", "dark"],
    strong: ["ground", "rock", "fire", "fighting", "poison"],
  },
  {
    id: 80,
    name: "slowbro",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/80.png",
    types: ["water", "psychic"],
    weight: 785,
    height: 16,
    abilities: ["oblivious", "own-tempo", "regenerator"],
    stats: [
      { name: "hp", value: 95 },
      { name: "attack", value: 75 },
      { name: "defense", value: 110 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 30 },
    ],
    weak: ["grass", "electric", "bug", "ghost", "dark"],
    strong: ["ground", "rock", "fire", "fighting", "poison"],
  },
  {
    id: 81,
    name: "magnemite",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/81.png",
    types: ["electric", "steel"],
    weight: 60,
    height: 3,
    abilities: ["magnet-pull", "sturdy", "analytic"],
    stats: [
      { name: "hp", value: 25 },
      { name: "attack", value: 35 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 45 },
    ],
    weak: ["ground", "fighting", "ground", "fire"],
    strong: ["flying", "water", "rock", "ice", "fairy"],
  },
  {
    id: 82,
    name: "magneton",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/82.png",
    types: ["electric", "steel"],
    weight: 600,
    height: 10,
    abilities: ["magnet-pull", "sturdy", "analytic"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 60 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 120 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 70 },
    ],
    weak: ["ground", "fighting", "ground", "fire"],
    strong: ["flying", "water", "rock", "ice", "fairy"],
  },
  {
    id: 83,
    name: "farfetchd",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/83.png",
    types: ["normal", "flying"],
    weight: 150,
    height: 8,
    abilities: ["keen-eye", "inner-focus", "defiant"],
    stats: [
      { name: "hp", value: 52 },
      { name: "attack", value: 90 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 58 },
      { name: "special-defense", value: 62 },
      { name: "speed", value: 60 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 84,
    name: "doduo",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/84.png",
    types: ["normal", "flying"],
    weight: 392,
    height: 14,
    abilities: ["run-away", "early-bird", "tangled-feet"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 85 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 35 },
      { name: "speed", value: 75 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 85,
    name: "dodrio",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/85.png",
    types: ["normal", "flying"],
    weight: 852,
    height: 18,
    abilities: ["run-away", "early-bird", "tangled-feet"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 110 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 60 },
      { name: "speed", value: 110 },
    ],
    weak: ["fighting", "rock", "electric", "ice"],
    strong: ["fighting", "bug", "grass"],
  },
  {
    id: 86,
    name: "seel",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/86.png",
    types: ["water"],
    weight: 900,
    height: 11,
    abilities: ["thick-fat", "hydration", "ice-body"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 45 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 45 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 87,
    name: "dewgong",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/87.png",
    types: ["water", "ice"],
    weight: 1200,
    height: 17,
    abilities: ["thick-fat", "hydration", "ice-body"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 70 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 70 },
    ],
    weak: ["grass", "electric", "fighting", "rock", "steel", "fire"],
    strong: ["ground", "rock", "fire", "flying", "ground", "grass", "dragon"],
  },
  {
    id: 88,
    name: "grimer",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/88.png",
    types: ["poison"],
    weight: 300,
    height: 9,
    abilities: ["stench", "sticky-hold", "poison-touch"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 80 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 25 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 89,
    name: "muk",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/89.png",
    types: ["poison"],
    weight: 300,
    height: 12,
    abilities: ["stench", "sticky-hold", "poison-touch"],
    stats: [
      { name: "hp", value: 105 },
      { name: "attack", value: 105 },
      { name: "defense", value: 75 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 50 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 90,
    name: "shellder",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/90.png",
    types: ["water"],
    weight: 40,
    height: 3,
    abilities: ["shell-armor", "skill-link", "overcoat"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 65 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 40 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 91,
    name: "cloyster",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/91.png",
    types: ["water", "ice"],
    weight: 1325,
    height: 15,
    abilities: ["shell-armor", "skill-link", "overcoat"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 95 },
      { name: "defense", value: 180 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 70 },
    ],
    weak: ["grass", "electric", "fighting", "rock", "steel", "fire"],
    strong: ["ground", "rock", "fire", "flying", "ground", "grass", "dragon"],
  },
  {
    id: 92,
    name: "gastly",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/92.png",
    types: ["ghost", "poison"],
    weight: 1,
    height: 13,
    abilities: ["levitate"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 35 },
      { name: "defense", value: 30 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 35 },
      { name: "speed", value: 80 },
    ],
    weak: ["ghost", "dark", "ground", "psychic"],
    strong: ["ghost", "psychic", "grass", "fairy"],
  },
  {
    id: 93,
    name: "haunter",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/93.png",
    types: ["ghost", "poison"],
    weight: 1,
    height: 16,
    abilities: ["levitate"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 50 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 115 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 95 },
    ],
    weak: ["ghost", "dark", "ground", "psychic"],
    strong: ["ghost", "psychic", "grass", "fairy"],
  },
  {
    id: 94,
    name: "gengar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/94.png",
    types: ["ghost", "poison"],
    weight: 405,
    height: 15,
    abilities: ["cursed-body"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 65 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 130 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 110 },
    ],
    weak: ["ghost", "dark", "ground", "psychic"],
    strong: ["ghost", "psychic", "grass", "fairy"],
  },
  {
    id: 95,
    name: "onix",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/95.png",
    types: ["rock", "ground"],
    weight: 2100,
    height: 88,
    abilities: ["rock-head", "sturdy", "weak-armor"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 45 },
      { name: "defense", value: 160 },
      { name: "special-attack", value: 30 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 70 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "water",
      "grass",
      "ice",
    ],
    strong: [
      "flying",
      "bug",
      "fire",
      "ice",
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
    ],
  },
  {
    id: 96,
    name: "drowzee",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/96.png",
    types: ["psychic"],
    weight: 324,
    height: 10,
    abilities: ["insomnia", "forewarn", "inner-focus"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 48 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 43 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 42 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 97,
    name: "hypno",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/97.png",
    types: ["psychic"],
    weight: 756,
    height: 16,
    abilities: ["insomnia", "forewarn", "inner-focus"],
    stats: [
      { name: "hp", value: 85 },
      { name: "attack", value: 73 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 73 },
      { name: "special-defense", value: 115 },
      { name: "speed", value: 67 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 98,
    name: "krabby",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/98.png",
    types: ["water"],
    weight: 65,
    height: 4,
    abilities: ["hyper-cutter", "shell-armor", "sheer-force"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 105 },
      { name: "defense", value: 90 },
      { name: "special-attack", value: 25 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 50 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 99,
    name: "kingler",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/99.png",
    types: ["water"],
    weight: 600,
    height: 13,
    abilities: ["hyper-cutter", "shell-armor", "sheer-force"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 130 },
      { name: "defense", value: 115 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 75 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 100,
    name: "voltorb",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/100.png",
    types: ["electric"],
    weight: 104,
    height: 5,
    abilities: ["soundproof", "static", "aftermath"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 30 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 100 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 101,
    name: "electrode",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/101.png",
    types: ["electric"],
    weight: 666,
    height: 12,
    abilities: ["soundproof", "static", "aftermath"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 50 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 80 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 150 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 102,
    name: "exeggcute",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/102.png",
    types: ["grass", "psychic"],
    weight: 25,
    height: 4,
    abilities: ["chlorophyll", "harvest"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 40 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 40 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "bug", "ghost", "dark"],
    strong: ["ground", "rock", "water", "fighting", "poison"],
  },
  {
    id: 103,
    name: "exeggutor",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/103.png",
    types: ["grass", "psychic"],
    weight: 1200,
    height: 20,
    abilities: ["chlorophyll", "harvest"],
    stats: [
      { name: "hp", value: 95 },
      { name: "attack", value: 95 },
      { name: "defense", value: 85 },
      { name: "special-attack", value: 125 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 55 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice", "bug", "ghost", "dark"],
    strong: ["ground", "rock", "water", "fighting", "poison"],
  },
  {
    id: 104,
    name: "cubone",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/104.png",
    types: ["ground"],
    weight: 65,
    height: 4,
    abilities: ["rock-head", "lightning-rod", "battle-armor"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 50 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 35 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 105,
    name: "marowak",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/105.png",
    types: ["ground"],
    weight: 450,
    height: 10,
    abilities: ["rock-head", "lightning-rod", "battle-armor"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 80 },
      { name: "defense", value: 110 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 45 },
    ],
    weak: ["water", "grass", "ice"],
    strong: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 106,
    name: "hitmonlee",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/106.png",
    types: ["fighting"],
    weight: 498,
    height: 15,
    abilities: ["limber", "reckless", "unburden"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 120 },
      { name: "defense", value: 53 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 110 },
      { name: "speed", value: 87 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 107,
    name: "hitmonchan",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/107.png",
    types: ["fighting"],
    weight: 502,
    height: 14,
    abilities: ["keen-eye", "iron-fist", "inner-focus"],
    stats: [
      { name: "hp", value: 50 },
      { name: "attack", value: 105 },
      { name: "defense", value: 79 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 110 },
      { name: "speed", value: 76 },
    ],
    weak: ["flying", "psychic", "fairy"],
    strong: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 108,
    name: "lickitung",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/108.png",
    types: ["normal"],
    weight: 655,
    height: 12,
    abilities: ["own-tempo", "oblivious", "cloud-nine"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 55 },
      { name: "defense", value: 75 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 30 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 109,
    name: "koffing",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/109.png",
    types: ["poison"],
    weight: 10,
    height: 6,
    abilities: ["levitate", "neutralizing-gas", "stench"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 65 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 35 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 110,
    name: "weezing",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/110.png",
    types: ["poison"],
    weight: 95,
    height: 12,
    abilities: ["levitate", "neutralizing-gas", "stench"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 90 },
      { name: "defense", value: 120 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 60 },
    ],
    weak: ["ground", "psychic"],
    strong: ["grass", "fairy"],
  },
  {
    id: 111,
    name: "rhyhorn",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/111.png",
    types: ["ground", "rock"],
    weight: 1150,
    height: 10,
    abilities: ["lightning-rod", "rock-head", "reckless"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 85 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 30 },
      { name: "special-defense", value: 30 },
      { name: "speed", value: 25 },
    ],
    weak: [
      "water",
      "grass",
      "ice",
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
    ],
    strong: [
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
      "flying",
      "bug",
      "fire",
      "ice",
    ],
  },
  {
    id: 112,
    name: "rhydon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/112.png",
    types: ["ground", "rock"],
    weight: 1200,
    height: 19,
    abilities: ["lightning-rod", "rock-head", "reckless"],
    stats: [
      { name: "hp", value: 105 },
      { name: "attack", value: 130 },
      { name: "defense", value: 120 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 40 },
    ],
    weak: [
      "water",
      "grass",
      "ice",
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
    ],
    strong: [
      "poison",
      "rock",
      "steel",
      "fire",
      "electric",
      "flying",
      "bug",
      "fire",
      "ice",
    ],
  },
  {
    id: 113,
    name: "chansey",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/113.png",
    types: ["normal"],
    weight: 346,
    height: 11,
    abilities: ["natural-cure", "serene-grace", "healer"],
    stats: [
      { name: "hp", value: 250 },
      { name: "attack", value: 5 },
      { name: "defense", value: 5 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 105 },
      { name: "speed", value: 50 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 114,
    name: "tangela",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/114.png",
    types: ["grass"],
    weight: 350,
    height: 10,
    abilities: ["chlorophyll", "leaf-guard", "regenerator"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 55 },
      { name: "defense", value: 115 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 40 },
      { name: "speed", value: 60 },
    ],
    weak: ["flying", "poison", "bug", "fire", "ice"],
    strong: ["ground", "rock", "water"],
  },
  {
    id: 115,
    name: "kangaskhan",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/115.png",
    types: ["normal"],
    weight: 800,
    height: 22,
    abilities: ["early-bird", "scrappy", "inner-focus"],
    stats: [
      { name: "hp", value: 105 },
      { name: "attack", value: 95 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 90 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 116,
    name: "horsea",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/116.png",
    types: ["water"],
    weight: 80,
    height: 4,
    abilities: ["swift-swim", "sniper", "damp"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 40 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 25 },
      { name: "speed", value: 60 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 117,
    name: "seadra",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/117.png",
    types: ["water"],
    weight: 250,
    height: 12,
    abilities: ["poison-point", "sniper", "damp"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 65 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 85 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 118,
    name: "goldeen",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/118.png",
    types: ["water"],
    weight: 150,
    height: 6,
    abilities: ["swift-swim", "water-veil", "lightning-rod"],
    stats: [
      { name: "hp", value: 45 },
      { name: "attack", value: 67 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 35 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 63 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 119,
    name: "seaking",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/119.png",
    types: ["water"],
    weight: 390,
    height: 13,
    abilities: ["swift-swim", "water-veil", "lightning-rod"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 92 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 68 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 120,
    name: "staryu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/120.png",
    types: ["water"],
    weight: 345,
    height: 8,
    abilities: ["illuminate", "natural-cure", "analytic"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 45 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 85 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 121,
    name: "starmie",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/121.png",
    types: ["water", "psychic"],
    weight: 800,
    height: 11,
    abilities: ["illuminate", "natural-cure", "analytic"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 75 },
      { name: "defense", value: 85 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 115 },
    ],
    weak: ["grass", "electric", "bug", "ghost", "dark"],
    strong: ["ground", "rock", "fire", "fighting", "poison"],
  },
  {
    id: 122,
    name: "mr-mime",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/122.png",
    types: ["psychic", "fairy"],
    weight: 545,
    height: 13,
    abilities: ["soundproof", "filter", "technician"],
    stats: [
      { name: "hp", value: 40 },
      { name: "attack", value: 45 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 120 },
      { name: "speed", value: 90 },
    ],
    weak: ["bug", "ghost", "dark", "poison", "steel"],
    strong: ["fighting", "poison", "fighting", "dragon", "dark"],
  },
  {
    id: 123,
    name: "scyther",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/123.png",
    types: ["bug", "flying"],
    weight: 560,
    height: 15,
    abilities: ["swarm", "technician", "steadfast"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 110 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 80 },
      { name: "speed", value: 105 },
    ],
    weak: ["flying", "rock", "fire", "rock", "electric", "ice"],
    strong: ["grass", "psychic", "dark", "fighting", "bug", "grass"],
  },
  {
    id: 124,
    name: "jynx",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/124.png",
    types: ["ice", "psychic"],
    weight: 406,
    height: 14,
    abilities: ["oblivious", "forewarn", "dry-skin"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 50 },
      { name: "defense", value: 35 },
      { name: "special-attack", value: 115 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 95 },
    ],
    weak: ["fighting", "rock", "steel", "fire", "bug", "ghost", "dark"],
    strong: ["flying", "ground", "grass", "dragon", "fighting", "poison"],
  },
  {
    id: 125,
    name: "electabuzz",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/125.png",
    types: ["electric"],
    weight: 300,
    height: 11,
    abilities: ["static", "vital-spirit"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 83 },
      { name: "defense", value: 57 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 105 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 126,
    name: "magmar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/126.png",
    types: ["fire"],
    weight: 445,
    height: 13,
    abilities: ["flame-body", "vital-spirit"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 95 },
      { name: "defense", value: 57 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 93 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 127,
    name: "pinsir",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/127.png",
    types: ["bug"],
    weight: 550,
    height: 15,
    abilities: ["hyper-cutter", "mold-breaker", "moxie"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 125 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 85 },
    ],
    weak: ["flying", "rock", "fire"],
    strong: ["grass", "psychic", "dark"],
  },
  {
    id: 128,
    name: "tauros",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/128.png",
    types: ["normal"],
    weight: 884,
    height: 14,
    abilities: ["intimidate", "anger-point", "sheer-force"],
    stats: [
      { name: "hp", value: 75 },
      { name: "attack", value: 100 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 40 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 110 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 129,
    name: "magikarp",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/129.png",
    types: ["water"],
    weight: 100,
    height: 9,
    abilities: ["swift-swim", "rattled"],
    stats: [
      { name: "hp", value: 20 },
      { name: "attack", value: 10 },
      { name: "defense", value: 55 },
      { name: "special-attack", value: 15 },
      { name: "special-defense", value: 20 },
      { name: "speed", value: 80 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 130,
    name: "gyarados",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/130.png",
    types: ["water", "flying"],
    weight: 2350,
    height: 65,
    abilities: ["intimidate", "moxie"],
    stats: [
      { name: "hp", value: 95 },
      { name: "attack", value: 125 },
      { name: "defense", value: 79 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 81 },
    ],
    weak: ["grass", "electric", "rock", "electric", "ice"],
    strong: ["ground", "rock", "fire", "fighting", "bug", "grass"],
  },
  {
    id: 131,
    name: "lapras",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/131.png",
    types: ["water", "ice"],
    weight: 2200,
    height: 25,
    abilities: ["water-absorb", "shell-armor", "hydration"],
    stats: [
      { name: "hp", value: 130 },
      { name: "attack", value: 85 },
      { name: "defense", value: 80 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 60 },
    ],
    weak: ["grass", "electric", "fighting", "rock", "steel", "fire"],
    strong: ["ground", "rock", "fire", "flying", "ground", "grass", "dragon"],
  },
  {
    id: 132,
    name: "ditto",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/132.png",
    types: ["normal"],
    weight: 40,
    height: 3,
    abilities: ["limber", "imposter"],
    stats: [
      { name: "hp", value: 48 },
      { name: "attack", value: 48 },
      { name: "defense", value: 48 },
      { name: "special-attack", value: 48 },
      { name: "special-defense", value: 48 },
      { name: "speed", value: 48 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 133,
    name: "eevee",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/133.png",
    types: ["normal"],
    weight: 65,
    height: 3,
    abilities: ["run-away", "adaptability", "anticipation"],
    stats: [
      { name: "hp", value: 55 },
      { name: "attack", value: 55 },
      { name: "defense", value: 50 },
      { name: "special-attack", value: 45 },
      { name: "special-defense", value: 65 },
      { name: "speed", value: 55 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 134,
    name: "vaporeon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/134.png",
    types: ["water"],
    weight: 290,
    height: 10,
    abilities: ["water-absorb", "hydration"],
    stats: [
      { name: "hp", value: 130 },
      { name: "attack", value: 65 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 110 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 65 },
    ],
    weak: ["grass", "electric"],
    strong: ["ground", "rock", "fire"],
  },
  {
    id: 135,
    name: "jolteon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/135.png",
    types: ["electric"],
    weight: 245,
    height: 8,
    abilities: ["volt-absorb", "quick-feet"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 65 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 110 },
      { name: "special-defense", value: 95 },
      { name: "speed", value: 130 },
    ],
    weak: ["ground"],
    strong: ["flying", "water"],
  },
  {
    id: 136,
    name: "flareon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/136.png",
    types: ["fire"],
    weight: 250,
    height: 9,
    abilities: ["flash-fire", "guts"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 130 },
      { name: "defense", value: 60 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 110 },
      { name: "speed", value: 65 },
    ],
    weak: ["ground", "rock", "water"],
    strong: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 137,
    name: "porygon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/137.png",
    types: ["normal"],
    weight: 365,
    height: 8,
    abilities: ["trace", "download", "analytic"],
    stats: [
      { name: "hp", value: 65 },
      { name: "attack", value: 60 },
      { name: "defense", value: 70 },
      { name: "special-attack", value: 85 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 40 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 138,
    name: "omanyte",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/138.png",
    types: ["rock", "water"],
    weight: 75,
    height: 4,
    abilities: ["swift-swim", "shell-armor", "weak-armor"],
    stats: [
      { name: "hp", value: 35 },
      { name: "attack", value: 40 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 90 },
      { name: "special-defense", value: 55 },
      { name: "speed", value: 35 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "grass",
      "electric",
    ],
    strong: ["flying", "bug", "fire", "ice", "ground", "rock", "fire"],
  },
  {
    id: 139,
    name: "omastar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/139.png",
    types: ["rock", "water"],
    weight: 350,
    height: 10,
    abilities: ["swift-swim", "shell-armor", "weak-armor"],
    stats: [
      { name: "hp", value: 70 },
      { name: "attack", value: 60 },
      { name: "defense", value: 125 },
      { name: "special-attack", value: 115 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 55 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "grass",
      "electric",
    ],
    strong: ["flying", "bug", "fire", "ice", "ground", "rock", "fire"],
  },
  {
    id: 140,
    name: "kabuto",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/140.png",
    types: ["rock", "water"],
    weight: 115,
    height: 5,
    abilities: ["swift-swim", "battle-armor", "weak-armor"],
    stats: [
      { name: "hp", value: 30 },
      { name: "attack", value: 80 },
      { name: "defense", value: 90 },
      { name: "special-attack", value: 55 },
      { name: "special-defense", value: 45 },
      { name: "speed", value: 55 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "grass",
      "electric",
    ],
    strong: ["flying", "bug", "fire", "ice", "ground", "rock", "fire"],
  },
  {
    id: 141,
    name: "kabutops",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/141.png",
    types: ["rock", "water"],
    weight: 405,
    height: 13,
    abilities: ["swift-swim", "battle-armor", "weak-armor"],
    stats: [
      { name: "hp", value: 60 },
      { name: "attack", value: 115 },
      { name: "defense", value: 105 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 80 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "grass",
      "electric",
    ],
    strong: ["flying", "bug", "fire", "ice", "ground", "rock", "fire"],
  },
  {
    id: 142,
    name: "aerodactyl",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/142.png",
    types: ["rock", "flying"],
    weight: 590,
    height: 18,
    abilities: ["rock-head", "pressure", "unnerve"],
    stats: [
      { name: "hp", value: 80 },
      { name: "attack", value: 105 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 60 },
      { name: "special-defense", value: 75 },
      { name: "speed", value: 130 },
    ],
    weak: [
      "fighting",
      "ground",
      "steel",
      "water",
      "grass",
      "rock",
      "electric",
      "ice",
    ],
    strong: ["flying", "bug", "fire", "ice", "fighting", "bug", "grass"],
  },
  {
    id: 143,
    name: "snorlax",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/143.png",
    types: ["normal"],
    weight: 4600,
    height: 21,
    abilities: ["immunity", "thick-fat", "gluttony"],
    stats: [
      { name: "hp", value: 160 },
      { name: "attack", value: 110 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 65 },
      { name: "special-defense", value: 110 },
      { name: "speed", value: 30 },
    ],
    weak: ["fighting"],
    strong: [],
  },
  {
    id: 144,
    name: "articuno",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/144.png",
    types: ["ice", "flying"],
    weight: 554,
    height: 17,
    abilities: ["pressure", "snow-cloak"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 85 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 95 },
      { name: "special-defense", value: 125 },
      { name: "speed", value: 85 },
    ],
    weak: ["fighting", "rock", "steel", "fire", "rock", "electric", "ice"],
    strong: ["flying", "ground", "grass", "dragon", "fighting", "bug", "grass"],
  },
  {
    id: 145,
    name: "zapdos",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/145.png",
    types: ["electric", "flying"],
    weight: 526,
    height: 16,
    abilities: ["pressure", "static"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 90 },
      { name: "defense", value: 85 },
      { name: "special-attack", value: 125 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 100 },
    ],
    weak: ["ground", "rock", "electric", "ice"],
    strong: ["flying", "water", "fighting", "bug", "grass"],
  },
  {
    id: 146,
    name: "moltres",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/146.png",
    types: ["fire", "flying"],
    weight: 600,
    height: 20,
    abilities: ["pressure", "flame-body"],
    stats: [
      { name: "hp", value: 90 },
      { name: "attack", value: 100 },
      { name: "defense", value: 90 },
      { name: "special-attack", value: 125 },
      { name: "special-defense", value: 85 },
      { name: "speed", value: 90 },
    ],
    weak: ["ground", "rock", "water", "rock", "electric", "ice"],
    strong: ["bug", "steel", "grass", "ice", "fighting", "bug", "grass"],
  },
  {
    id: 147,
    name: "dratini",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/147.png",
    types: ["dragon"],
    weight: 33,
    height: 18,
    abilities: ["shed-skin", "marvel-scale"],
    stats: [
      { name: "hp", value: 41 },
      { name: "attack", value: 64 },
      { name: "defense", value: 45 },
      { name: "special-attack", value: 50 },
      { name: "special-defense", value: 50 },
      { name: "speed", value: 50 },
    ],
    weak: ["ice", "dragon", "fairy"],
    strong: ["dragon"],
  },
  {
    id: 148,
    name: "dragonair",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/148.png",
    types: ["dragon"],
    weight: 165,
    height: 40,
    abilities: ["shed-skin", "marvel-scale"],
    stats: [
      { name: "hp", value: 61 },
      { name: "attack", value: 84 },
      { name: "defense", value: 65 },
      { name: "special-attack", value: 70 },
      { name: "special-defense", value: 70 },
      { name: "speed", value: 70 },
    ],
    weak: ["ice", "dragon", "fairy"],
    strong: ["dragon"],
  },
  {
    id: 149,
    name: "dragonite",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/149.png",
    types: ["dragon", "flying"],
    weight: 2100,
    height: 22,
    abilities: ["inner-focus", "multiscale"],
    stats: [
      { name: "hp", value: 91 },
      { name: "attack", value: 134 },
      { name: "defense", value: 95 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 80 },
    ],
    weak: ["ice", "dragon", "fairy", "rock", "electric", "ice"],
    strong: ["dragon", "fighting", "bug", "grass"],
  },
  {
    id: 150,
    name: "mewtwo",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/150.png",
    types: ["psychic"],
    weight: 1220,
    height: 20,
    abilities: ["pressure", "unnerve"],
    stats: [
      { name: "hp", value: 106 },
      { name: "attack", value: 110 },
      { name: "defense", value: 90 },
      { name: "special-attack", value: 154 },
      { name: "special-defense", value: 90 },
      { name: "speed", value: 130 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
  {
    id: 151,
    name: "mew",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/151.png",
    types: ["psychic"],
    weight: 40,
    height: 4,
    abilities: ["synchronize"],
    stats: [
      { name: "hp", value: 100 },
      { name: "attack", value: 100 },
      { name: "defense", value: 100 },
      { name: "special-attack", value: 100 },
      { name: "special-defense", value: 100 },
      { name: "speed", value: 100 },
    ],
    weak: ["bug", "ghost", "dark"],
    strong: ["fighting", "poison"],
  },
];
